-- -----------------------------------------------------------
-- Introduction
-- The first century spans from the year 1 up to and including the year 100, the second century - from the year 101 up to and including the year 200, 
-- etc.
-- 
-- Task
-- Given a year, return the century it is in.
-- 
-- Examples
-- 1705 --> 18
-- 1900 --> 19
-- 1601 --> 17
-- 2000 --> 20
-- 
-- In SQL, you will be given a table years with a column yr for the year. Return a table with a column century.
-- -----------------------------------------------------------

SELECT CEIL((yr - 1) / 100) + 1 AS Century FROM years;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------