-- -----------------------------------------------------------
-- Your task is to sort the information in the provided table 'companies' by number of employees (high to low). Returned table should be in the same 
-- format as provided:
-- 
-- companies table schema
-- 
-- id
-- ceo
-- motto
-- employees
-- 
-- Solution should use pure SQL. Ruby is only used in test cases.
-- -----------------------------------------------------------

SELECT * FROM companies ORDER BY employees DESC;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------