-- -----------------------------------------------------------
-- Nathan loves cycling.
-- 
-- Because Nathan knows it is important to stay hydrated, he drinks 0.5 litres of water per hour of cycling.
-- 
-- You get given the time in hours and you need to return the number of litres Nathan will drink, rounded to the smallest value.
-- 
-- For example:
-- 
-- hours = 3 ----> liters = 1
-- 
-- hours = 6.7---> liters = 3
-- 
-- hours = 11.8--> liters = 5
-- 
-- You have to return 3 columns: id, hours and liters (not litres, it's a difference from the kata description)
-- -----------------------------------------------------------

SELECT *, FLOOR(hours * 0.5) AS liters FROM cycling;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------