-- -----------------------------------------------------------
-- Enumerate me
-- We have a list of numbers. But each number should have its own number to identify it.
-- 
-- Sounds crazy? Maybe, but that's what you should do: assign each row a number from 1 to infinity and name it id.
-- 
-- For example:
-- 
-- |----|-----|
-- | 1  | 32 |
-- | 2  | 44  |
-- | 3  | 56 |
-- |----|-----|
-- 
-- You should not use create or alter, only select.
-- 
-- So the output schema is:
-- 
-- |--------------|
-- | numbers      |
-- |----|---------|
-- | id | integer |
-- | n  | integer |
-- |----|---------|
-- -----------------------------------------------------------

-- select all of the numbers

SELECT ROW_NUMBER() OVER(ORDER BY n) AS id, * FROM numbers;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------