-- -----------------------------------------------------------
-- Greetings Grasshopper!
-- Using only SQL, write a query that returns all rows in the custid, custname, and custstate columns from the customers table.
-- 
-- Table Description for customers:
-- 
-- Column				Data Type				Size				Sample
-- custid				integer					8					4
-- custname				string					50					Anakin Skywalker
-- custstate			string					50					Tatooine
-- custard				string					50					R2-D2
-- 
-- Your solution should contain only SQL.
-- -----------------------------------------------------------

SELECT custid, custname, custstate FROM customers;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------