-- -----------------------------------------------------------
-- You are given a table of persons which includes their respective age. Your task is to return the list of people, age 30 through 50, using the BETWEEN 
-- keyword.
-- 
-- The schema for the persons table is as follows:
-- 
-- id
-- name
-- age
-- 
-- The resulting table should have two columns as follows:
-- 
-- name
-- age
-- 
-- Order by age, highest to lowest.
-- 
-- Note: Your solution should use pure SQL. Ruby is used within the test cases to do the actual testing.
-- -----------------------------------------------------------

SELECT name, age FROM persons
WHERE age BETWEEN 30 AND 50 ORDER BY age DESC;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------