-- -----------------------------------------------------------
-- You work at a book store. It's the end of the month, and you need to find out the 5 bestselling books at your store. Use a select statement to list 
-- names, authors, and number of copies sold of the 5 books which were sold most.
-- 
-- books table schema
-- name
-- author
-- copies_sold
-- 
-- NOTE: Your solution should use pure SQL. Ruby is used within the test cases just to validate your answer.
-- -----------------------------------------------------------

SELECT * FROM books ORDER BY copies_sold DESC LIMIT 5;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------