-- -----------------------------------------------------------
-- Given a demographics table in the following format:
-- 
-- ** demographics table schema **
-- 
-- id
-- name
-- birthday
-- race
-- 
-- you need to return the same table where all text fields (name & race) are changed to the ascii code of their first byte.
-- 
-- e.g. Verlie = 86 Warren = 87 Horace = 72 Tracy = 84
-- -----------------------------------------------------------

SELECT *, ASCII(name) AS name, ASCII(race) AS race FROM demographics;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------