-- -----------------------------------------------------------
-- Given a demographics table in the following format:
-- 
-- ** demographics table schema **
-- 
-- id
-- name
-- birthday
-- race
-- 
-- you need to return a table that shows a count of each race represented, ordered by the count in descending order as:
-- 
-- ** output table schema **
-- 
-- race
-- count
-- -----------------------------------------------------------

SELECT race, COUNT(race) FROM demographics
GROUP BY race ORDER BY COUNT(race) DESC;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------