-- -----------------------------------------------------------
-- You have access to a table of monsters as follows:
-- 
-- monsters schema
-- 
-- id
-- name
-- legs
-- arms
-- characteristics
-- 
-- In each row, the characteristic column has a single comma. Your job is to find it using position(). You must return a table with the format as follows:
-- 
-- output schema
-- 
-- id
-- name
-- comma
-- 
-- The comma column will contain the position of the comma within the characteristics string. Order the results by comma.
-- -----------------------------------------------------------

SELECT id, name, POSITION(',' IN characteristics)
AS comma FROM monsters ORDER BY comma;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------