-- -----------------------------------------------------------
-- For this challenge you need to create a simple SELECT statement that will return all columns from the products 
-- table, and join to the companies table so that you can return the company name.
-- 
-- products table schema
-- id
-- name
-- isbn
-- company_id
-- price
-- 
-- companies table schema
-- id
-- name
-- 
-- You should return all product fields as well as the company name as "company_name".
-- 
-- NOTE: Your solution should use pure SQL. Ruby is used within the test cases to do the actual testing.
-- -----------------------------------------------------------

SELECT products.*, companies.name AS company_name FROM products
JOIN companies ON products.company_id = companies.id;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------