-- -----------------------------------------------------------
-- You are given a table random\_string that has the following format:
-- 
-- random_string schema
-- text
-- 
-- The text field holds a single row which contains a random string.
-- 
-- Your task is to take the random string and split it on each vowel (a, e, i, o, u) then the resultant substrings will be contained in the output table, 
-- formatted as:
-- 
-- output table schema
-- results
-- 
-- Note that the vowels should be removed.
-- 
-- If there are no vowels, there will only be one row returned. Where there are multiple vowels in succession, you will see empty rows. A row should be 
-- created on each break, whether there is content in the row or not.
-- 
-- Regex is advised but not mandatory.
-- -----------------------------------------------------------

SELECT REGEXP_SPLIT_TO_TABLE(TEXT, '[aAeEiIoOuU]')
AS results FROM random_string;

-- -----------------------------------------------------------
-- License
-- Tasks are the property of Codewars (https://www.codewars.com/) 
-- and users of this resource.
-- 
-- All solution code in this repository 
-- is the personal property of Vladimir Rukavishnikov
-- (vladimirrukavishnikovmail@gmail.com).
-- 
-- Copyright (C) 2022 Vladimir Rukavishnikov
-- 
-- This file is part of the HungryVovka/Codewars-SQL
-- (https://github.com/HungryVovka/Codewars-SQL)
-- 
-- License is GNU General Public License v3.0
-- (https://github.com/HungryVovka/Codewars-SQL/blob/main/LICENSE)
-- 
-- You should have received a copy of the GNU General Public License v3.0
-- along with this code. If not, see http://www.gnu.org/licenses/
-- -----------------------------------------------------------